In [13]:
import numpy as np
import pandas as pd
df=pd.read_csv('C:/Users/LAPTOP/Desktop/SalarySense-ML/data/row/job_salary_prediction_dataset.csv')
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [14]:
df.isna().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.nunique()

job_title               12
experience_years        21
education_level          5
skills_count            19
industry                10
company_size             5
location                10
remote_work              3
certifications           6
salary              118956
dtype: int64

In [ ]:
categorical_columns = df.select_dtypes(include='str').columns
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- job_title ---
job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

--- education_level ---
education_level
Master         50352
High School    50065
Bachelor       49950
PhD            49857
Diploma        49776
Name: count, dtype: int64

--- industry ---
industry
Finance          25393
Consulting       25258
Media            25034
Manufacturing    25024
Technology       24903
Government       24901
Healthcare       24898
Education        24889
Telecom          24859
Retail           24841
Name: count, dtype: int64

--- company_size ---
company_size
Large         50254
Small         50235
Medium        50027
Enterprise    49875
Startup       49609
Name: count, dtype: int64

--- location ---
location
Australia      25258
Canada         25165
Sweden         25100
Remote         25065
Singapore      25035
USA            24931
UK             24927
India          24895
Netherlands    24861
Germany        24763
Name: count, dtype: int64

--- remote_work ---
remote_work
No        83621
Hybrid    83476
Yes       82903
Name: count, dtype: int64

In [22]:
df.describe().round(2)

       experience_years  skills_count  certifications     salary
count         250000.00     250000.00       250000.00  250000.00
mean              10.01         10.00            2.49  145718.08
std                6.06          5.48            1.71   37407.95
min                0.00          1.00            0.00   31867.00
25%                5.00          5.00            1.00  119358.00
50%               10.00         10.00            2.00  143453.00
75%               15.00         15.00            4.00  169492.00
max               20.00         19.00            5.00  333046.00

- The dataset contains 250,000 rows and 10 columns.
- The target variable is "salary".
- The dataset contains both numerical and categorical features.
- There are no missing values.
- There are no duplicated rows.
- There are no high-cardinality categorical features.